[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aid_expertise_search"
version = "0.1.0"
description = ""
authors = [
    {name = "Åsmund Mjøs", email = "Aasmund.mjos@sintef.no"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.135.2",
    "uvicorn==0.24.0",
    "pandas==2.2.3",
    "numpy==2.3.5",
    "hdbscan==0.8.40",
    "umap-learn==0.5.7",
    "nltk==3.9.1",
    "sentence-transformers==3.3.1",
    "openai==1.86.0",
    "python-dotenv==1.1.0",
    "langchain==0.3.26",
    "langchain-core==0.3.66",
    "langchain-openai==0.3.24",
    "langchain-text-splitters==0.3.8",
    "langsmith==0.4.1",
    "scikit-learn==1.7.1",
    "matplotlib==3.10.3",
    "langgraph==0.5.4",
    "streamlit==1.47.1",
    "pyfiglet==1.0.4",
    "bm25s==0.3.2.post1",
    "PyMuPDF==1.26.6",
    "pymupdf-layout==1.26.6",
    "pymupdf4llm==0.2.9"

]

[tool.setuptools.packages.find]
where = ["src"]